title: Quarantine Life!!
author: Ellen
email: ellenlewisc@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Staying entertained in quarantine

# social links
github_username:  ellenlewisc # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
